package services

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/akmatori/akmatori/internal/database"
	"gopkg.in/yaml.v3"
)

// SkillFrontmatter represents the YAML frontmatter of a SKILL.md file
type SkillFrontmatter struct {
	Name        string            `yaml:"name"`
	Description string            `yaml:"description"`
	Metadata    map[string]string `yaml:"metadata,omitempty"`
}

// GetSkillPrompt reads the prompt for a skill
// For incident-manager system skill, returns the hardcoded default
// For regular skills, reads from SKILL.md file
func (s *SkillService) GetSkillPrompt(name string) (string, error) {
	// Incident-manager uses hardcoded prompt (not editable)
	if name == "incident-manager" {
		return database.DefaultIncidentManagerPrompt, nil
	}

	// Regular skill - read from SKILL.md
	skillPath := filepath.Join(s.GetSkillDir(name), "SKILL.md")
	content, err := os.ReadFile(skillPath)
	if err != nil {
		return "", fmt.Errorf("failed to read SKILL.md: %w", err)
	}

	// Parse and extract body (after frontmatter)
	parts := strings.SplitN(string(content), "---", 3)
	if len(parts) >= 3 {
		body := strings.TrimSpace(parts[2])
		// Strip auto-generated resource instructions section if present
		body = stripAutoGeneratedSections(body)
		return body, nil
	}
	return string(content), nil
}

// stripAutoGeneratedSections removes auto-generated sections from the skill body
// to get only the user-defined prompt. Strips both old "Quick Start" (Python imports)
// and new "Assigned Tools" sections.
func stripAutoGeneratedSections(body string) string {
	// Strip old-format "Quick Start" section (Python imports from pre-pi-mono era)
	const quickStartMarker = "## Quick Start"
	const endMarker = "---\n"

	if strings.HasPrefix(body, quickStartMarker) {
		idx := strings.Index(body, endMarker)
		if idx == -1 {
			return body
		}
		body = strings.TrimSpace(body[idx+len(endMarker):])
		return stripAutoGeneratedSections(body)
	}

	// Strip new-format "Assigned Tools" section (auto-generated tool list)
	const toolsMarker = "\n\n## Assigned Tools\n"
	if idx := strings.Index(body, toolsMarker); idx != -1 {
		body = strings.TrimSpace(body[:idx])
	}

	return body
}

// UpdateSkillPrompt updates the prompt for a skill
// For incident-manager system skill, this is a no-op (prompt is hardcoded)
// For regular skills, writes to SKILL.md file
func (s *SkillService) UpdateSkillPrompt(name, prompt string) error {
	// Incident-manager prompt is hardcoded, can't be updated
	if name == "incident-manager" {
		return nil
	}

	// Regular skill - write to SKILL.md
	skill, err := s.GetSkill(name)
	if err != nil {
		return err
	}

	// Sync asset symlinks for [[filename]] references in prompt
	if err := s.SyncSkillAssets(name, prompt); err != nil {
		slog.Warn("failed to sync skill assets", "err", err)
		// Continue even if asset sync fails - it's not critical
	}

	// Generate new SKILL.md with updated body and current tools
	tools := s.getSkillTools(name)
	skillMd := s.generateSkillMd(name, skill.Description, prompt, tools)
	skillPath := filepath.Join(s.GetSkillDir(name), "SKILL.md")

	if err := os.WriteFile(skillPath, []byte(skillMd), 0644); err != nil {
		return fmt.Errorf("failed to write SKILL.md: %w", err)
	}

	return nil
}

// generateSkillMd generates a SKILL.md file with YAML frontmatter and user prompt body
// Tools are called via Python wrappers through the bash tool, with usage examples per tool type
func (s *SkillService) generateSkillMd(name, description, body string, tools []database.ToolInstance) string {
	frontmatter := SkillFrontmatter{
		Name:        name,
		Description: description,
		Metadata: map[string]string{
			"short-description": truncateString(description, 50),
		},
	}

	yamlBytes, err := yaml.Marshal(frontmatter)
	if err != nil {
		slog.Error("failed to marshal SKILL.md frontmatter", "skill", name, "err", err)
		yamlBytes = []byte(fmt.Sprintf("name: %s\n", name))
	}

	// Transform [[filename]] references to markdown links [filename](assets/filename)
	resolvedBody := s.contextService.ResolveReferencesToMarkdownLinks(body)

	// List assigned tools with Python usage examples for per-skill routing
	var toolsSection strings.Builder
	var enabledTools []database.ToolInstance
	for _, tool := range tools {
		if tool.Enabled && tool.ToolType.ID != 0 {
			enabledTools = append(enabledTools, tool)
		}
	}
	if len(enabledTools) > 0 {
		toolsSection.WriteString("\n\n## Assigned Tools\n")
		for _, tool := range enabledTools {
			toolsSection.WriteString(fmt.Sprintf("\n### %s (ID: %d, type: %s)\n", tool.Name, tool.ID, tool.ToolType.Name))
			if details := extractToolDetails(tool); details != "" {
				toolsSection.WriteString(details)
			}
			toolsSection.WriteString(generateToolUsageExample(tool))
		}
	}

	return fmt.Sprintf("---\n%s---\n\n%s%s\n", string(yamlBytes), resolvedBody, toolsSection.String())
}

// sshHasConfiguredHosts checks if the SSH tool instance has any configured hosts.
func sshHasConfiguredHosts(tool database.ToolInstance) bool {
	if tool.Settings == nil {
		return false
	}
	hostsData, ok := tool.Settings["ssh_hosts"]
	if !ok {
		return false
	}
	hostsJSON, err := json.Marshal(hostsData)
	if err != nil {
		return false
	}
	var hosts []map[string]interface{}
	if err := json.Unmarshal(hostsJSON, &hosts); err != nil {
		return false
	}
	for _, h := range hosts {
		if addr, _ := h["address"].(string); strings.TrimSpace(addr) != "" {
			return true
		}
	}
	return false
}

// sshAllHostsAllowWrite checks if ALL hosts in an SSH tool instance have allow_write_commands enabled.
// Returns false if any host is read-only (the default), if settings are missing, or if there are no hosts.
func sshAllHostsAllowWrite(tool database.ToolInstance) bool {
	if tool.Settings == nil {
		return false
	}
	hostsData, ok := tool.Settings["ssh_hosts"]
	if !ok {
		return false
	}
	hostsJSON, err := json.Marshal(hostsData)
	if err != nil {
		return false
	}
	var hosts []map[string]interface{}
	if err := json.Unmarshal(hostsJSON, &hosts); err != nil {
		return false
	}
	if len(hosts) == 0 {
		return false
	}
	hasValidHost := false
	for _, h := range hosts {
		// Skip placeholder rows with blank addresses (same filter as runtime)
		if addr, _ := h["address"].(string); strings.TrimSpace(addr) == "" {
			continue
		}
		hasValidHost = true
		allow, ok := h["allow_write_commands"].(bool)
		if !ok || !allow {
			return false
		}
	}
	if !hasValidHost {
		return false
	}
	return true
}

// generateToolUsageExample creates Python code block showing how to call the tool
func generateToolUsageExample(tool database.ToolInstance) string {
	typeName := tool.ToolType.Name
	id := tool.ID

	switch typeName {
	case "ssh":
		adhocEnabled, _ := tool.Settings["allow_adhoc_connections"].(bool)
		adhocWriteEnabled, _ := tool.Settings["adhoc_allow_write_commands"].(bool)
		hasConfiguredHosts := sshHasConfiguredHosts(tool)
		configuredHostsWritable := sshAllHostsAllowWrite(tool)

		// If neither configured hosts nor ad-hoc connections are available,
		// the tool is misconfigured — tell the agent explicitly.
		if !hasConfiguredHosts && !adhocEnabled {
			return fmt.Sprintf(`
**SSH tool "%s" (instance %d) is not configured** — no hosts are defined and ad-hoc connections are disabled.
Ask the operator to add SSH hosts or enable ad-hoc connections in the tool settings before this tool can be used.
`, tool.Name, id)
		}

		// Build read-only warnings separately for configured hosts and ad-hoc
		var readOnlyNote string
		readOnlyCommands := `Allowed: cat, head, tail, grep, find, ls, ps, top, df, free, netstat, ss, uptime,
vmstat, iostat, mpstat, sar, pidstat, journalctl, dmesg, nproc, lscpu, getconf,
docker ps/logs/inspect, kubectl get/describe/logs, systemctl status.
For CPU core count use ` + "`nproc`" + ` or ` + "`lscpu`" + ` (not /proc/cpuinfo parsing).
`
		if hasConfiguredHosts && !configuredHostsWritable && adhocEnabled && adhocWriteEnabled {
			readOnlyNote = "\n**Read-only mode is enabled for configured hosts** — only diagnostic commands are allowed.\n" + readOnlyCommands +
				"Ad-hoc connections allow write commands.\n"
		} else if hasConfiguredHosts && configuredHostsWritable && adhocEnabled && !adhocWriteEnabled {
			readOnlyNote = "\n**Read-only mode is enabled for ad-hoc connections** — only diagnostic commands are allowed on ad-hoc targets.\n" + readOnlyCommands
		} else if !configuredHostsWritable && !(adhocEnabled && adhocWriteEnabled) {
			readOnlyNote = "\n**Read-only mode is enabled** — only diagnostic commands are allowed.\n" + readOnlyCommands
		}

		// Build examples based on what's available
		var configuredExamples string
		if hasConfiguredHosts {
			configuredExamples = fmt.Sprintf(`
result = execute_command("uptime", tool_instance_id=%d)
result = execute_command("df -h", servers=["hostname"], tool_instance_id=%d)
result = test_connectivity(tool_instance_id=%d)
result = get_server_info(tool_instance_id=%d)`, id, id, id, id)
		}

		var adhocExample string
		if adhocEnabled {
			adhocExample = fmt.Sprintf(`
# Ad-hoc: connect to any server by hostname/FQDN/IP
result = execute_command("uptime", servers=["<hostname-or-ip>"], tool_instance_id=%d)
result = test_connectivity(servers=["<server1>", "<server2>"], tool_instance_id=%d)
result = get_server_info(servers=["<hostname-or-ip>"], tool_instance_id=%d)`, id, id, id)
		}

		return fmt.Sprintf(`
Usage (via bash tool):
`+"```python"+`
from ssh import execute_command, test_connectivity, get_server_info
%s%s
`+"```"+`
%s`, configuredExamples, adhocExample, readOnlyNote)
	case "zabbix":
		return fmt.Sprintf(`
Usage (via bash tool):
`+"```python"+`
from zabbix import get_hosts, get_problems, get_history, get_items, get_items_batch, get_triggers, api_request

result = get_hosts(tool_instance_id=%d)
result = get_problems(severity_min=3, tool_instance_id=%d)
result = get_items_batch(searches=["cpu", "memory"], tool_instance_id=%d)
result = get_history(itemids=["67890"], limit=10, tool_instance_id=%d)
result = get_items(hostids=["12345"], search={"key_": "cpu"}, tool_instance_id=%d)
result = get_triggers(hostids=["12345"], only_true=True, tool_instance_id=%d)
result = api_request("host.get", params={"output": ["hostid", "host"]}, tool_instance_id=%d)
`+"```"+`
`, id, id, id, id, id, id, id)
	case "victoria_metrics":
		return fmt.Sprintf(`
Usage (via bash tool):
`+"```python"+`
from victoriametrics import instant_query, range_query, label_values, series, api_request

result = instant_query("up", tool_instance_id=%d)
result = range_query("rate(http_requests_total[5m])", start="2h", end="now", step="1m", tool_instance_id=%d)
result = label_values("__name__", tool_instance_id=%d)
result = series(match="up", tool_instance_id=%d)
result = api_request("/api/v1/status/tsdb", tool_instance_id=%d)
`+"```"+`
`, id, id, id, id, id)
	default:
		return fmt.Sprintf("When using %s tools, pass `tool_instance_id: %d` to target this instance.\n", typeName, id)
	}
}

// extractToolDetails extracts non-secret, agent-relevant details from a tool instance's settings.
// For SSH: lists configured hostnames so the agent knows which servers it can target.
// For other tool types (zabbix, etc.): no extra details needed — the agent interacts via MCP Gateway
// tools and doesn't need internal connection details like URLs or endpoints.
func extractToolDetails(tool database.ToolInstance) string {
	if tool.Settings == nil {
		return ""
	}

	typeName := tool.ToolType.Name

	switch typeName {
	case "ssh":
		var details strings.Builder

		// Extract hostnames from ssh_hosts array — agent needs these for server targeting
		hostsData, ok := tool.Settings["ssh_hosts"]
		if ok {
			hostsJSON, err := json.Marshal(hostsData)
			if err == nil {
				var hosts []map[string]interface{}
				if err := json.Unmarshal(hostsJSON, &hosts); err == nil {
					var hostnames []string
					for _, h := range hosts {
						// Skip placeholder rows with blank addresses (same filter as runtime)
						if addr, _ := h["address"].(string); strings.TrimSpace(addr) == "" {
							continue
						}
						if hostname, ok := h["hostname"].(string); ok && hostname != "" {
							hostnames = append(hostnames, hostname)
						}
					}
					if len(hostnames) > 0 {
						details.WriteString(fmt.Sprintf("Configured hosts: %s\n", strings.Join(hostnames, ", ")))
					}
				}
			}
		}

		// Note ad-hoc connection capability when enabled
		if allow, ok := tool.Settings["allow_adhoc_connections"].(bool); ok && allow {
			user := "root"
			if u, ok := tool.Settings["adhoc_default_user"].(string); ok && u != "" {
				user = u
			}
			port := 22
			if p, ok := tool.Settings["adhoc_default_port"].(float64); ok && p > 0 {
				port = int(p)
			}
			details.WriteString(fmt.Sprintf("Ad-hoc connections enabled: can connect to any server (default user: %s, port: %d)\n", user, port))
			if allowWrite, ok := tool.Settings["adhoc_allow_write_commands"].(bool); ok && allowWrite {
				details.WriteString("Ad-hoc write commands: allowed\n")
			} else {
				details.WriteString("Ad-hoc write commands: read-only (diagnostic commands only)\n")
			}
		}

		return details.String()
	}

	return ""
}

// truncateString truncates a string to max rune length, safe for multi-byte UTF-8
func truncateString(s string, max int) string {
	runes := []rune(s)
	if len(runes) <= max {
		return s
	}
	if max < 4 {
		return string(runes[:max])
	}
	return string(runes[:max-3]) + "..."
}
