package services

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/akmatori/akmatori/internal/database"
	"gopkg.in/yaml.v3"
)

// SkillFrontmatter represents the YAML frontmatter of a SKILL.md file
type SkillFrontmatter struct {
	Name        string            `yaml:"name"`
	Description string            `yaml:"description"`
	Metadata    map[string]string `yaml:"metadata,omitempty"`
}

// GetSkillPrompt reads the prompt for a skill
// For incident-manager system skill, returns the hardcoded default
// For regular skills, reads from SKILL.md file
func (s *SkillService) GetSkillPrompt(name string) (string, error) {
	// Incident-manager uses hardcoded prompt (not editable)
	if name == "incident-manager" {
		return database.DefaultIncidentManagerPrompt, nil
	}

	// Regular skill - read from SKILL.md
	skillPath := filepath.Join(s.GetSkillDir(name), "SKILL.md")
	content, err := os.ReadFile(skillPath)
	if err != nil {
		return "", fmt.Errorf("failed to read SKILL.md: %w", err)
	}

	// Parse and extract body (after frontmatter)
	parts := strings.SplitN(string(content), "---", 3)
	if len(parts) >= 3 {
		body := strings.TrimSpace(parts[2])
		// Strip auto-generated resource instructions section if present
		body = stripAutoGeneratedSections(body)
		return body, nil
	}
	return string(content), nil
}

// stripAutoGeneratedSections removes auto-generated sections from the skill body
// to get only the user-defined prompt. Strips both old "Quick Start" (Python imports)
// and new "Assigned Tools" sections.
func stripAutoGeneratedSections(body string) string {
	// Strip old-format "Quick Start" section (Python imports from pre-pi-mono era)
	const quickStartMarker = "## Quick Start"
	const endMarker = "---\n"

	if strings.HasPrefix(body, quickStartMarker) {
		idx := strings.Index(body, endMarker)
		if idx == -1 {
			return body
		}
		body = strings.TrimSpace(body[idx+len(endMarker):])
		return stripAutoGeneratedSections(body)
	}

	// Strip new-format "Assigned Tools" section (auto-generated tool list)
	const toolsMarker = "\n\n## Assigned Tools\n"
	if idx := strings.Index(body, toolsMarker); idx != -1 {
		body = strings.TrimSpace(body[:idx])
	}

	return body
}

// UpdateSkillPrompt updates the prompt for a skill
// For incident-manager system skill, this is a no-op (prompt is hardcoded)
// For regular skills, writes to SKILL.md file
func (s *SkillService) UpdateSkillPrompt(name, prompt string) error {
	// Incident-manager prompt is hardcoded, can't be updated
	if name == "incident-manager" {
		return nil
	}

	// Regular skill - write to SKILL.md
	skill, err := s.GetSkill(name)
	if err != nil {
		return err
	}

	// Sync asset symlinks for [[filename]] references in prompt
	if err := s.SyncSkillAssets(name, prompt); err != nil {
		slog.Warn("failed to sync skill assets", "err", err)
		// Continue even if asset sync fails - it's not critical
	}

	// Generate new SKILL.md with updated body and current tools
	tools := s.getSkillTools(name)
	skillMd := s.generateSkillMd(name, skill.Description, prompt, tools)
	skillPath := filepath.Join(s.GetSkillDir(name), "SKILL.md")

	if err := os.WriteFile(skillPath, []byte(skillMd), 0644); err != nil {
		return fmt.Errorf("failed to write SKILL.md: %w", err)
	}

	return nil
}

// generateSkillMd generates a SKILL.md file with YAML frontmatter and user prompt body
// Tools are called via gateway_call through the pi-mono extension, with usage examples per tool type
func (s *SkillService) generateSkillMd(name, description, body string, tools []database.ToolInstance) string {
	frontmatter := SkillFrontmatter{
		Name:        name,
		Description: description,
		Metadata: map[string]string{
			"short-description": truncateString(description, 50),
		},
	}

	yamlBytes, err := yaml.Marshal(frontmatter)
	if err != nil {
		slog.Error("failed to marshal SKILL.md frontmatter", "skill", name, "err", err)
		yamlBytes = []byte(fmt.Sprintf("name: %s\n", name))
	}

	// Transform [[filename]] references to markdown links [filename](assets/filename)
	resolvedBody := s.contextService.ResolveReferencesToMarkdownLinks(body)

	// List assigned tools with gateway_call usage examples for per-skill routing
	var toolsSection strings.Builder
	var enabledTools []database.ToolInstance
	for _, tool := range tools {
		if tool.Enabled && tool.ToolType.ID != 0 {
			enabledTools = append(enabledTools, tool)
		}
	}
	if len(enabledTools) > 0 {
		toolsSection.WriteString("\n\n## Assigned Tools\n")
		toolsSection.WriteString("\nYour assigned tools are listed below with full parameter schemas and gateway_call examples. Use these examples directly — no need to call list_tools_for_tool_type or get_tool_detail for tools listed here.\n")
		toolsSection.WriteString("Use `execute_script` to run multi-step scripts with built-in `gateway_call()` for batch operations.\n")
		for _, tool := range enabledTools {
			logicalName := tool.LogicalName
			if logicalName == "" {
				logicalName = tool.Name
			}
			toolsSection.WriteString(fmt.Sprintf("\n### %s (logical_name: \"%s\", type: %s)\n", tool.Name, logicalName, tool.ToolType.Name))
			if details := extractToolDetails(tool); details != "" {
				toolsSection.WriteString(details)
			}
			toolsSection.WriteString(generateToolUsageExample(tool))
		}
	}

	return fmt.Sprintf("---\n%s---\n\n%s%s\n", string(yamlBytes), resolvedBody, toolsSection.String())
}

// sshHasConfiguredHosts checks if the SSH tool instance has any configured hosts.
func sshHasConfiguredHosts(tool database.ToolInstance) bool {
	if tool.Settings == nil {
		return false
	}
	hostsData, ok := tool.Settings["ssh_hosts"]
	if !ok {
		return false
	}
	hostsJSON, err := json.Marshal(hostsData)
	if err != nil {
		return false
	}
	var hosts []map[string]interface{}
	if err := json.Unmarshal(hostsJSON, &hosts); err != nil {
		return false
	}
	for _, h := range hosts {
		if addr, _ := h["address"].(string); strings.TrimSpace(addr) != "" {
			return true
		}
	}
	return false
}

// sshAllHostsAllowWrite checks if ALL hosts in an SSH tool instance have allow_write_commands enabled.
// Returns false if any host is read-only (the default), if settings are missing, or if there are no hosts.
func sshAllHostsAllowWrite(tool database.ToolInstance) bool {
	if tool.Settings == nil {
		return false
	}
	hostsData, ok := tool.Settings["ssh_hosts"]
	if !ok {
		return false
	}
	hostsJSON, err := json.Marshal(hostsData)
	if err != nil {
		return false
	}
	var hosts []map[string]interface{}
	if err := json.Unmarshal(hostsJSON, &hosts); err != nil {
		return false
	}
	if len(hosts) == 0 {
		return false
	}
	hasValidHost := false
	for _, h := range hosts {
		// Skip placeholder rows with blank addresses (same filter as runtime)
		if addr, _ := h["address"].(string); strings.TrimSpace(addr) == "" {
			continue
		}
		hasValidHost = true
		allow, ok := h["allow_write_commands"].(bool)
		if !ok || !allow {
			return false
		}
	}
	return hasValidHost
}

// generateToolUsageExample creates usage examples showing how to call the tool via gateway_call
func generateToolUsageExample(tool database.ToolInstance) string {
	typeName := tool.ToolType.Name
	logicalName := tool.LogicalName
	if logicalName == "" {
		logicalName = tool.Name
	}

	switch typeName {
	case "ssh":
		adhocEnabled, _ := tool.Settings["allow_adhoc_connections"].(bool)
		adhocWriteEnabled, _ := tool.Settings["adhoc_allow_write_commands"].(bool)
		hasConfiguredHosts := sshHasConfiguredHosts(tool)
		configuredHostsWritable := sshAllHostsAllowWrite(tool)

		// If neither configured hosts nor ad-hoc connections are available,
		// the tool is misconfigured — tell the agent explicitly.
		if !hasConfiguredHosts && !adhocEnabled {
			return fmt.Sprintf(`
**SSH tool "%s" is not configured** — no hosts are defined and ad-hoc connections are disabled.
Ask the operator to add SSH hosts or enable ad-hoc connections in the tool settings before this tool can be used.
`, tool.Name)
		}

		// Build read-only warnings separately for configured hosts and ad-hoc
		var readOnlyNote string
		readOnlyCommands := `Allowed: cat, head, tail, grep, find, ls, ps, top, df, free, netstat, ss, uptime,
vmstat, iostat, mpstat, sar, pidstat, journalctl, dmesg, nproc, lscpu, getconf,
docker ps/logs/inspect, kubectl get/describe/logs, systemctl status.
For CPU core count use ` + "`nproc`" + ` or ` + "`lscpu`" + ` (not /proc/cpuinfo parsing).
`
		if hasConfiguredHosts && !configuredHostsWritable && adhocEnabled && adhocWriteEnabled {
			readOnlyNote = "\n**Read-only mode is enabled for configured hosts** — only diagnostic commands are allowed.\n" + readOnlyCommands +
				"Ad-hoc connections allow write commands.\n"
		} else if hasConfiguredHosts && configuredHostsWritable && adhocEnabled && !adhocWriteEnabled {
			readOnlyNote = "\n**Read-only mode is enabled for ad-hoc connections** — only diagnostic commands are allowed on ad-hoc targets.\n" + readOnlyCommands
		} else if !configuredHostsWritable && !(adhocEnabled && adhocWriteEnabled) {
			readOnlyNote = "\n**Read-only mode is enabled** — only diagnostic commands are allowed.\n" + readOnlyCommands
		}

		// Build examples based on what's available
		var configuredExamples string
		if hasConfiguredHosts {
			configuredExamples = fmt.Sprintf(`
gateway_call("ssh.execute_command", {"command": "uptime"}, "%s")
gateway_call("ssh.execute_command", {"command": "df -h", "servers": ["hostname"]}, "%s")
gateway_call("ssh.test_connectivity", {}, "%s")
gateway_call("ssh.get_server_info", {}, "%s")`, logicalName, logicalName, logicalName, logicalName)
		}

		var adhocExample string
		if adhocEnabled {
			adhocExample = fmt.Sprintf(`
# Ad-hoc: connect to any server by hostname/FQDN/IP
gateway_call("ssh.execute_command", {"command": "uptime", "servers": ["<hostname-or-ip>"]}, "%s")
gateway_call("ssh.test_connectivity", {"servers": ["<server1>", "<server2>"]}, "%s")
gateway_call("ssh.get_server_info", {"servers": ["<hostname-or-ip>"]}, "%s")`, logicalName, logicalName, logicalName)
		}

		return fmt.Sprintf(`
**Parameters:**
- `+"`execute_command`"+`: command* | servers
- `+"`test_connectivity`"+`: servers
- `+"`get_server_info`"+`: servers
(* = required)

Usage (via gateway_call):
`+"```"+`
%s%s
`+"```"+`
%s`, configuredExamples, adhocExample, readOnlyNote)
	case "zabbix":
		return fmt.Sprintf(`
**Parameters:**
- `+"`get_hosts`"+`: output, filter, search, start_search, limit
- `+"`get_problems`"+`: recent, severity_min, hostids, limit
- `+"`get_items`"+`: hostids, filter, search, start_search, output, limit
- `+"`get_items_batch`"+`: searches* | hostids, start_search, output, limit_per_search
- `+"`get_history`"+`: itemids* | history, time_from, time_till, limit, sortfield, sortorder
- `+"`get_triggers`"+`: hostids, only_true, min_severity, output
- `+"`api_request`"+`: method* | params
(* = required)

Usage (via gateway_call):
`+"```"+`
gateway_call("zabbix.get_hosts", {}, "%s")
gateway_call("zabbix.get_problems", {"severity_min": 3}, "%s")
gateway_call("zabbix.get_items_batch", {"searches": ["cpu", "memory"]}, "%s")
gateway_call("zabbix.get_history", {"itemids": ["67890"], "limit": 10}, "%s")
gateway_call("zabbix.get_items", {"hostids": ["12345"], "search": {"key_": "cpu"}}, "%s")
gateway_call("zabbix.get_triggers", {"hostids": ["12345"], "only_true": true}, "%s")
gateway_call("zabbix.api_request", {"method": "host.get", "params": {"output": ["hostid", "host"]}}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "victoria_metrics":
		return fmt.Sprintf(`
**Parameters:**
- `+"`instant_query`"+`: query* | time, step, timeout
- `+"`range_query`"+`: query*, start*, end*, step* | timeout
- `+"`label_values`"+`: label_name* | match, start, end
- `+"`series`"+`: match* | start, end
- `+"`api_request`"+`: path* | method, params
(* = required)

Usage (via gateway_call):
`+"```"+`
gateway_call("victoria_metrics.instant_query", {"query": "up"}, "%s")
gateway_call("victoria_metrics.range_query", {"query": "rate(http_requests_total[5m])", "start": "2h", "end": "now", "step": "1m"}, "%s")
gateway_call("victoria_metrics.label_values", {"label_name": "__name__"}, "%s")
gateway_call("victoria_metrics.series", {"match": "up"}, "%s")
gateway_call("victoria_metrics.api_request", {"path": "/api/v1/status/tsdb"}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName)
	default:
		return fmt.Sprintf("Use `gateway_call(\"%s.<tool_method>\", {<args>}, \"%s\")` to call this tool's methods.\n", typeName, logicalName)
	}
}

// extractToolDetails extracts non-secret, agent-relevant details from a tool instance's settings.
// For SSH: lists configured hostnames so the agent knows which servers it can target.
// For other tool types (zabbix, etc.): no extra details needed — the agent interacts via MCP Gateway
// tools and doesn't need internal connection details like URLs or endpoints.
func extractToolDetails(tool database.ToolInstance) string {
	if tool.Settings == nil {
		return ""
	}

	typeName := tool.ToolType.Name

	switch typeName {
	case "ssh":
		var details strings.Builder

		// Extract hostnames from ssh_hosts array — agent needs these for server targeting
		hostsData, ok := tool.Settings["ssh_hosts"]
		if ok {
			hostsJSON, err := json.Marshal(hostsData)
			if err == nil {
				var hosts []map[string]interface{}
				if err := json.Unmarshal(hostsJSON, &hosts); err == nil {
					var hostnames []string
					for _, h := range hosts {
						// Skip placeholder rows with blank addresses (same filter as runtime)
						if addr, _ := h["address"].(string); strings.TrimSpace(addr) == "" {
							continue
						}
						if hostname, ok := h["hostname"].(string); ok && hostname != "" {
							hostnames = append(hostnames, hostname)
						}
					}
					if len(hostnames) > 0 {
						details.WriteString(fmt.Sprintf("Configured hosts: %s\n", strings.Join(hostnames, ", ")))
					}
				}
			}
		}

		// Note ad-hoc connection capability when enabled
		if allow, ok := tool.Settings["allow_adhoc_connections"].(bool); ok && allow {
			user := "root"
			if u, ok := tool.Settings["adhoc_default_user"].(string); ok && u != "" {
				user = u
			}
			port := 22
			if p, ok := tool.Settings["adhoc_default_port"].(float64); ok && p > 0 {
				port = int(p)
			}
			details.WriteString(fmt.Sprintf("Ad-hoc connections enabled: can connect to any server (default user: %s, port: %d)\n", user, port))
			if allowWrite, ok := tool.Settings["adhoc_allow_write_commands"].(bool); ok && allowWrite {
				details.WriteString("Ad-hoc write commands: allowed\n")
			} else {
				details.WriteString("Ad-hoc write commands: read-only (diagnostic commands only)\n")
			}
		}

		return details.String()
	}

	return ""
}

// truncateString truncates a string to max rune length, safe for multi-byte UTF-8
func truncateString(s string, max int) string {
	runes := []rune(s)
	if len(runes) <= max {
		return s
	}
	if max < 4 {
		return string(runes[:max])
	}
	return string(runes[:max-3]) + "..."
}
